engines:
  eslint:
    enabled: true
    config:
      languages:
      - javascript
  duplication:
    enabled: true
    config:
      languages:
      - javascript
ratings:
   paths:
   - "components/*"
exclude_paths:
- "**/__tests__/"